### ISSUE TITLE
I met a train_local.py's issue by using data from huggingface

### ISSUE THREAD

**Issue by pussinmood** [jiajingk/train_vima#2]
when i use your train_local.py to train a model  and using option 1 to get dataset(500GB),i met RuntimeError:mat1 and mat2 shapes cannot be multiplied(1x3 and 2x256).If i use option 2 to get dataset,the run.py can not finish the data generating properly ,python will stop in the same point of perticular tasks,and with limited dataset ,the train_local.py's valid unweighted_loss and weighted_loss will keep growing high,after training ,the model can not do the work.will you tell me where went wrong,a noob needs your guidance~.~

**Comment by pussinmood** [comment]
is it about the calculation accuracy，my calculation accuracy is float32

**Comment by jiajingk** [comment]
> i met RuntimeError:mat1 and mat2 shapes cannot be multiplied(1x3 and 2x256)

Can you provide the stack trace so that I can locate which function trigger the error?

> the train_local.py's valid unweighted_loss and weighted_loss will keep growing high,after training 

It's probably overfitted. The best way to improve it is by adding more training data.

**Comment by pussinmood** [comment]
Traceback (most recent call last):
  File "/home/oem/data/fb/train-vima-02/train_local.py", line 515, in <module>
    main(os.path.join('.'))
  File "/home/oem/data/fb/train-vima-02/train_local.py", line 470, in main
    weighted_train_loss, train_logs = train_one_epoch(
  File "/home/oem/data/fb/train-vima-02/train_local.py", line 373, in train_one_epoch
    batch_loss, batch_logs = batch_forward(
  File "/home/oem/data/fb/train-vima-02/train_local.py", line 247, in batch_forward
    batch_forward_result = policy(data)
  File "/home/oem/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/oem/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/oem/data/fb/train-vima-02/playground/util/policy.py", line 63, in forward
    batch_preds = forward(
  File "/home/oem/data/fb/train-vima-02/playground/util/train.py", line 118, in forward
    tokens_out, decode_metas = decode_observation_and_prompt(
  File "/home/oem/data/fb/train-vima-02/playground/util/train.py", line 50, in decode_observation_and_prompt
    data_batch = prepare_batch_obs_action_tokens(trajs, device, policy)
  File "/home/oem/data/fb/train-vima-02/playground/util/prepare_batch.py", line 45, in prepare_batch_obs_action_tokens
    action_in, target_action = prepare_single_record_optional_action(traj, device, policy)
  File "/home/oem/data/fb/train-vima-02/playground/util/prepare_single.py", line 159, in prepare_single_record_optional_action
    action_tokens = policy.forward_action_token(action)
  File "/home/oem/data/fb/train-vima-02/vima/policy/vima_policy.py", line 271, in forward_action_token
    return self.action_encoder(self._de_discretize_actions(action))#将连续的动作离散化
  File "/home/oem/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/oem/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/oem/data/fb/train-vima-02/vima/nn/action_embd/action_embd.py", line 35, in forward
    [self._embed_dict[k](x_dict[k]) for k in sorted(x_dict.keys())], dim=-1
  File "/home/oem/data/fb/train-vima-02/vima/nn/action_embd/action_embd.py", line 35, in <listcomp>
    [self._embed_dict[k](x_dict[k]) for k in sorted(x_dict.keys())], dim=-1
  File "/home/oem/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/oem/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/oem/data/fb/train-vima-02/vima/nn/action_embd/action_embd.py", line 56, in forward
    return self._layer(x)
  File "/home/oem/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/oem/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/oem/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/home/oem/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/oem/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/oem/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x3 and 2x256)
这是我的报错结果（in case you are chinese just like me），Traceback is like this，thank you so much about your attention

**Comment by pussinmood** [comment]
i also wish to learn how to debug this kinds of issues by myself，desperately need your advices about which kind of videos or books i need to learn to improve myself?

**Comment by jiajingk** [comment]
你看一下用`scripts/data_generation/run.py`生成的数据和huggingface上下载的数据的各个attribute的shape是不是一样的，问题应该是出在这个地方

> i also wish to learn how to debug this kinds of issues by myself，desperately need your advices about which kind of videos or books i need to learn to improve myself?

可以跟着这个[教程](https://space.bilibili.com/1567748478/channel/seriesdetail?sid=358497)自己动手试一下各个模型是怎么用的  ，实践多了自然就学会了

**Comment by pussinmood** [comment]
> 你看一下用`scripts/data_generation/run.py`生成的数据和huggingface上下载的数据的各个attribute的shape是不是一样的，问题应该是出在这个地方
> 
> > i also wish to learn how to debug this kinds of issues by myself，desperately need your advices about which kind of videos or books i need to learn to improve myself?
> 
> 可以跟着这个[教程](https://space.bilibili.com/1567748478/channel/seriesdetail?sid=358497)自己动手试一下各个模型是怎么用的 ，实践多了自然就学会了

太感谢了，你的帮助让我重燃了希望～。～祝你生活愉快
